name: Test kernel clone

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clone kernel
      run: git clone --depth 1 https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git kernel
